### ISSUE TITLE
readme missing

### ISSUE THREAD

**Issue by ROCKS29** [DuanYuFi/AutoDecoder#2]
kindly add a readme mentioning cmds as to how to run this on windows/linux .. commands to run on windows n linux thanks

**Comment by DuanYuFi** [comment]
Thanks for your advice. This is a very simple decoder based on a school project. If you have requirements on auto decode, please see the module `magic` in [cyberchef](https://gchq.github.io/CyberChef/).
BTW, I will add a readme as soon as possible. Thank you.
